/**
 * ChatExport — exports DualMind conversations to various formats.
 * No external dependencies. Lazy-loaded on demand.
 */

export class ChatExport {
  constructor(state) {
    this.state = state;
  }

  getFilename(ext) {
    const date = new Date().toISOString().slice(0, 10);
    const mode = this.state.currentMode || 'battle';
    const turns = (this.state.turns?.length || this.state.direct?.length || 0);
    return `dualmind-${mode}-${date}-${turns}turns.${ext}`;
  }

  _buildMetadata() {
    const mode = this.state.currentMode || 'battle';
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const turns = this.state.turns || [];
    const direct = this.state.direct || [];

    let models = 'N/A';
    if (mode === 'battle' || mode === 'arena') {
      const first = turns[0];
      if (first) {
        const left = first.left?.modelName || 'Model A';
        const right = first.right?.modelName || 'Model B';
        models = `${left} vs ${right}`;
      }
    } else if (mode === 'direct') {
      const first = direct[0];
      models = first?.model || 'Unknown';
    }

    return {
      mode: mode.charAt(0).toUpperCase() + mode.slice(1),
      models,
      date,
      totalTurns: mode === 'direct' ? direct.length : turns.length,
    };
  }

  toMarkdown() {
    const meta = this._buildMetadata();
    const lines = [];

    lines.push('---');
    lines.push('Generated by DualMind Arena');
    lines.push(`Mode: ${meta.mode}`);
    lines.push(`Models: ${meta.models}`);
    lines.push(`Date: ${meta.date}`);
    lines.push(`Total Turns: ${meta.totalTurns}`);
    lines.push('---');
    lines.push('');

    if (this.state.currentMode === 'direct') {
      this.state.direct.forEach((msg, idx) => {
        lines.push(`## Message ${idx + 1} (${msg.role === 'user' ? 'You' : msg.model || 'Assistant'})`);
        lines.push('');
        lines.push(msg.text || '');
        lines.push('');
      });
    } else {
      this.state.turns.forEach((turn, idx) => {
        lines.push(`## Turn ${idx + 1}`);
        lines.push('');
        lines.push(`**Prompt:** ${turn.prompt || ''}`);
        lines.push('');

        if (turn.left) {
          lines.push(`### ${turn.left.modelName || 'Model A'} (Left)`);
          lines.push('');
          lines.push(turn.left.text || '');
          lines.push('');
        }

        if (turn.right) {
          lines.push(`### ${turn.right.modelName || 'Model B'} (Right)`);
          lines.push('');
          lines.push(turn.right.text || '');
          lines.push('');
        }

        if (turn.voteChoice) {
          lines.push(`**Vote:** ${turn.voteChoice}`);
          lines.push('');
        }

        lines.push('---');
        lines.push('');
      });
    }

    return lines.join('\n');
  }

  toJSON() {
    const meta = this._buildMetadata();
    const payload = {
      metadata: {
        generator: 'DualMind Arena',
        mode: meta.mode,
        models: meta.models,
        date: meta.date,
        totalTurns: meta.totalTurns,
        exportedAt: new Date().toISOString(),
      },
      turns: this.state.currentMode === 'direct' ? this.state.direct : this.state.turns,
    };
    return JSON.stringify(payload, null, 2);
  }

  toCSV() {
    const rows = [['turn', 'prompt', 'side', 'model', 'text', 'vote']];

    if (this.state.currentMode === 'direct') {
      this.state.direct.forEach((msg, idx) => {
        rows.push([
          idx + 1,
          '',
          msg.role === 'user' ? 'user' : 'assistant',
          msg.model || '',
          this._csvEscape(msg.text || ''),
          '',
        ]);
      });
    } else {
      this.state.turns.forEach((turn, idx) => {
        const prompt = this._csvEscape(turn.prompt || '');
        const vote = turn.voteChoice || '';

        if (turn.left) {
          rows.push([
            idx + 1,
            prompt,
            'left',
            turn.left.modelName || 'Model A',
            this._csvEscape(turn.left.text || ''),
            vote,
          ]);
        }
        if (turn.right) {
          rows.push([
            idx + 1,
            prompt,
            'right',
            turn.right.modelName || 'Model B',
            this._csvEscape(turn.right.text || ''),
            vote,
          ]);
        }
      });
    }

    return rows.map(row => row.map(v => `"${v}"`).join(',')).join('\n');
  }

  _csvEscape(str) {
    return String(str).replace(/"/g, '""').replace(/\n/g, ' ');
  }

  toHTML() {
    const meta = this._buildMetadata();
    const md = this.toMarkdown();

    const escMeta = (s) => String(s).replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const escBody = (s) => String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/\n/g, '<br>');

    let turnsHtml = '';
    if (this.state.currentMode === 'direct') {
      turnsHtml = this.state.direct.map((msg, idx) => `
        <div class="turn">
          <div class="role ${msg.role === 'user' ? 'user' : 'ai'}">${msg.role === 'user' ? 'You' : escMeta(msg.model || 'Assistant')}</div>
          <div class="bubble">${escBody(msg.text || '')}</div>
        </div>
      `).join('');
    } else {
      turnsHtml = this.state.turns.map((turn, idx) => `
        <div class="turn">
          <div class="prompt"><strong>Turn ${idx + 1}:</strong> ${escBody(turn.prompt || '')}</div>
          <div class="responses">
            ${turn.left ? `<div class="response left"><div class="model-name">${escMeta(turn.left.modelName || 'Model A')}</div><div class="text">${escBody(turn.left.text || '')}</div></div>` : ''}
            ${turn.right ? `<div class="response right"><div class="model-name">${escMeta(turn.right.modelName || 'Model B')}</div><div class="text">${escBody(turn.right.text || '')}</div></div>` : ''}
          </div>
          ${turn.voteChoice ? `<div class="vote">Vote: ${escMeta(turn.voteChoice)}</div>` : ''}
        </div>
      `).join('');
    }

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DualMind Export — ${escMeta(meta.mode)} ${escMeta(meta.date)}</title>
<style>
  body { font-family: system-ui, sans-serif; background: #0d0f1a; color: #e5e7eb; margin: 0; padding: 24px; line-height: 1.6; }
  .header { background: rgba(74,171,194,0.1); border: 1px solid rgba(74,171,194,0.3); border-radius: 12px; padding: 20px 24px; margin-bottom: 32px; }
  .header h1 { margin: 0 0 8px; font-size: 20px; color: #4AABC2; }
  .header p { margin: 0 0 4px; font-size: 14px; color: rgba(255,255,255,0.6); }
  .turn { margin-bottom: 32px; border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; overflow: hidden; }
  .prompt { background: rgba(74,171,194,0.08); padding: 12px 16px; font-size: 14px; color: rgba(255,255,255,0.8); }
  .responses { display: grid; grid-template-columns: 1fr 1fr; gap: 1px; background: rgba(255,255,255,0.08); }
  .response { background: #0a0a0a; padding: 16px; }
  .response.left { border-left: 3px solid #4AABC2; }
  .response.right { border-right: 3px solid #CB9275; }
  .model-name { font-size: 12px; font-weight: 600; color: rgba(255,255,255,0.5); text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }
  .text { font-size: 14px; color: rgba(255,255,255,0.85); }
  .vote { padding: 8px 16px; font-size: 12px; color: rgba(255,255,255,0.5); background: rgba(255,255,255,0.02); }
  .role { padding: 8px 16px; font-size: 12px; font-weight: 600; color: rgba(255,255,255,0.6); background: rgba(255,255,255,0.03); }
  .role.user { color: #4AABC2; }
  .role.ai { color: #CB9275; }
  .bubble { padding: 12px 16px; font-size: 14px; }
  @media (max-width: 640px) { .responses { grid-template-columns: 1fr; } }
</style>
</head>
<body>
<!-- Generated by DualMind Arena | Mode: ${escMeta(meta.mode)} | Models: ${escMeta(meta.models)} | Date: ${escMeta(meta.date)} -->
<div class="header">
  <h1>DualMind Arena Export</h1>
  <p>Mode: ${escMeta(meta.mode)}</p>
  <p>Models: ${escMeta(meta.models)}</p>
  <p>Date: ${escMeta(meta.date)}</p>
  <p>Total Turns: ${meta.totalTurns}</p>
</div>
${turnsHtml}
</body>
</html>`;
  }

  toPDF() {
    // Inject print-specific CSS and trigger window.print()
    const existing = document.getElementById('dm-print-style');
    if (!existing) {
      const style = document.createElement('style');
      style.id = 'dm-print-style';
      style.textContent = `
        @media print {
          body * { visibility: hidden; }
          #dm-print-frame, #dm-print-frame * { visibility: visible; }
          #dm-print-frame { position: absolute; left: 0; top: 0; width: 100%; }
        }
      `;
      document.head.appendChild(style);
    }

    let frame = document.getElementById('dm-print-frame');
    if (!frame) {
      frame = document.createElement('div');
      frame.id = 'dm-print-frame';
      document.body.appendChild(frame);
    }

    frame.innerHTML = this.toHTML();
    window.print();
  }

  download(format) {
    let content, mimeType, filename;

    switch (format) {
      case 'md':
        content = this.toMarkdown();
        mimeType = 'text/markdown;charset=utf-8';
        filename = this.getFilename('md');
        break;
      case 'json':
        content = this.toJSON();
        mimeType = 'application/json;charset=utf-8';
        filename = this.getFilename('json');
        break;
      case 'csv':
        content = this.toCSV();
        mimeType = 'text/csv;charset=utf-8';
        filename = this.getFilename('csv');
        break;
      case 'html':
        content = this.toHTML();
        mimeType = 'text/html;charset=utf-8';
        filename = this.getFilename('html');
        break;
      case 'pdf':
        this.toPDF();
        return;
      default:
        console.warn('Unknown export format:', format);
        return;
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
